library auto_route;

export 'src/common/common.dart';
export 'src/matcher/route_match.dart';
export 'src/navigation_failure.dart';
export 'src/route/page_route_info.dart';
export 'src/route/route_config.dart';
export 'src/route/route_data_scope.dart';
export 'src/router/auto_route_page.dart';
export 'src/router/auto_router_x.dart';
export 'src/router/controller/controller_scope.dart';
export 'src/router/controller/routing_controller.dart';
export 'src/router/parser/route_information_parser.dart';
export 'src/router/provider/auto_route_information_provider.dart';
export 'src/router/widgets/auto_back_button.dart';
export 'src/router/widgets/auto_leading_button.dart';
export 'src/router/widgets/auto_router.dart';
export 'src/router/widgets/auto_route_navigator.dart';
export 'src/router/widgets/auto_tabs_router.dart';
export 'src/router/widgets/auto_tabs_scaffold.dart';
export 'src/router/widgets/wrapped_route.dart';
export 'src/router/widgets/custom_cupertino_transitions_builder.dart'
    show NoShadowCupertinoPageTransitionsBuilder;
export 'src/router/widgets/custom_tab_bar_view.dart';
