// Mocks generated by Mockito 5.4.5 from annotations
// in auto_route/test/simple_router/route_observer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:auto_route/auto_route.dart' as _i2;
import 'package:flutter/widgets.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AutoRouterObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoRouterObserver extends _i1.Mock implements _i2.AutoRouterObserver {
  @override
  void didInitTabRoute(
    _i2.TabPageRoute? route,
    _i2.TabPageRoute? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(#didInitTabRoute, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTabRoute(
    _i2.TabPageRoute? route,
    _i2.TabPageRoute? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(#didChangeTabRoute, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPush(_i3.Route<dynamic>? route, _i3.Route<dynamic>? previousRoute) => super.noSuchMethod(
        Invocation.method(#didPush, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(_i3.Route<dynamic>? route, _i3.Route<dynamic>? previousRoute) => super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i3.Route<dynamic>? route,
    _i3.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(#didRemove, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i3.Route<dynamic>? newRoute,
    _i3.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(#didReplace, [], {
          #newRoute: newRoute,
          #oldRoute: oldRoute,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i3.Route<dynamic>? topRoute,
    _i3.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i3.Route<dynamic>? route,
    _i3.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(#didStartUserGesture, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(#didStopUserGesture, []),
        returnValueForMissingStub: null,
      );
}
