include: package:flutter_lints/flutter.yaml
formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    unawaited_futures: true

