targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:

#          enable_cached_builds: true
        generate_for:
          - lib/**_page.dart
          - lib/**router.dart
      auto_route_generator:auto_router_generator:
        options:
          ignore_for_file:
            - rule-1
            - rule-2
        #          enable_cached_builds: true
        generate_for:
          - lib/**router.dart
