builders:
  auto_route_generator:
    import: "package:auto_route_generator/builder.dart"
    runs_before:
      [
        "auto_route_generator:auto_router_generator",
        "auto_route_generator:auto_router_module_generator",
      ]
    builder_factories: ["autoRouteBuilder"]
    build_extensions: { ".dart": [".route.json"] }
    auto_apply: dependents
    build_to: cache

  auto_router_generator:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: ["autoRouterBuilder"]
    build_extensions: { ".dart": [ ".gr.dart" ] }
    auto_apply: dependents
    build_to: source

